
service: ses-email-processing

provider:
  name: aws
  runtime: nodejs6.10
  profile: sls
  stage: dev
  region: us-east-1
  environment:
    BUCKET: mail-cloudly.tech

  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:*
    Resource: "*"

functions:
  receiveEmail:
    handler: index.handler
    events:
    - s3: ${self:provider.environment.BUCKET}

